version: '3.8'

services:
  oban-exporter-dev-container:
    build: .
    init: true
    privileged: true
    command: sleep infinity
    network_mode: service:postgres
    volumes:
      - ..:/home/vscode/workspace:cached